spring:
  mongodb:
    username: devdad
    password: devdad
    host: localhost
    port: 27018
    database: customer
    authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # spring.json.trusted.packages: '*' # Good for developement, allows everything
        spring.json.trusted.packages: "com.devdad.ecommerce" # Only allows specific packages
        spring.json.type.mapping: orderConfirmation:com.devdad.ecommerce.kafka.OrderConfirmationDTO,paymentConfirmation:com.devdad.ecommerce.kafka.PaymentNotificationRequestDTO
  mail:
    host: localhost
    port: 1025
    username: devdad
    password: devdad
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040
