services:
  postgres:
    container_name: ms_pg_sql
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ms_ecomm:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-equinox
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - internal
    depends_on:
      - postgres
    restart: unless-stopped

  mongodb:
    container_name: mongo_db
    image: mongo:7.0
    ports:
      - "27018:27017"
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: devdad
      MONGO_INITDB_ROOT_PASSWORD: devdad
    networks:
      internal:
        aliases:
          - mongo

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: devdad
      ME_CONFIG_MONGODB_ADMINPASSWORD: devdad
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - internal
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - internal

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094" # useful for dev as we can access kafka from the outside for testing purposes
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Controls __consumer_offsets topic replication (the one failing)
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # Same issue affects transaction state topic
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # Minimum in-sync replicas must also be 1 for single broker
    networks:
      - internal

networks:
  internal:
    driver: bridge
    name: internal

volumes:
  ms_ecomm:
    driver: local
  # Allows us to persist pgadmin data so need to re-add servers every single time
  pgadmin-data:
    driver: local
  mongo:
    driver: local
